### ISSUE TITLE
Update for Ionic 3

### ISSUE THREAD

**Issue by fredroo** [chroa/twitter-connect-plugin#1]
please update this project to work with twitter login

look this
https://ionicframework.com/docs/native/twitter-connect/

**Comment by fredroo** [comment]
@chroa look this, please help me

**Comment by fredroo** [comment]
https://github.com/ManifestWebDesign/twitter-connect-plugin/pull/61

**Comment by chroa** [comment]
Hey there! I am sort of new into this plugin mobile development thingy, but I am taking a look into it. :)
Can you tell me why isn't it working?

**Comment by fredroo** [comment]
twitter connect to auth acessToken not work, i need this to login social with twitter

my code implementation

look:

```
    loginTwitter():Promise<any> {
      return this.twitter.login()
      .then((response: TwitterConnectResponse) => {
        let accessToken = response.token;
        return this.userResource
            .register(accessToken, 'twitter')
            .then(token => this.jwtClient.setToken(token));
      })
      .catch((error) => {
          console.log(error);
      });
    }

    logoutTwitter():Promise<any>{
      return this.twitter.logout().then(() => {
            console.log("logged out");
        });
    }
```

**Comment by fredroo** [comment]
https://github.com/jmtt89/cordovaTwitter maybe this project help you

**Comment by fredroo** [comment]
@ManifestWebDesign help us

**Comment by chroa** [comment]
@fredroo I have made a simple Ionic project (Ionic version is 3.9.2), added my plugin and it is correctly performing the login authentication. I have inserted the example javascript of the README into the run function of my app:

````
.run(function($ionicPlatform) {
  $ionicPlatform.ready(function() {
    if(window.cordova && window.cordova.plugins.Keyboard) {
      // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
      // for form inputs)
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);

      // Don't remove this line unless you know what you are doing. It stops the viewport
      // from snapping when text inputs are focused. Ionic handles this internally for
      // a much nicer keyboard experience.
      cordova.plugins.Keyboard.disableScroll(true);

      //test twitter login - only added this part
      TwitterConnect.login(
        function(result) {
          console.log('Successful login!');
          console.log(result);
        },
        function(error) {
          console.log('Error logging in');
          console.log(error);
        }
      );
      
    }
    if(window.StatusBar) {
      StatusBar.styleDefault();
    }
  });
})
````

**Comment by fredroo** [comment]
@chroa  in you project use this:
https://github.com/chroa/twitter-connect-plugin#troubleshooting ?

**Comment by chroa** [comment]
I have not used that. Just created a new project, added the plugin and made the call on the run function.
It seems that the plugin is working on Ionic 3 projects, it's probably your code that is failing somewhere.
Where is that code? And where did you put that file?

**Comment by fredroo** [comment]
@chroa sorry my error

my old code put click function in icon, correct was button

**Comment by chroa** [comment]
Is it working now? :)

**Comment by fredroo** [comment]
yes thanks a lot

**Comment by chroa** [comment]
Awesome! And no problem :)
