### ISSUE TITLE
What would be causing this plugin install error?

### ISSUE THREAD

**Issue by rolinger** [chroa/twitter-connect-plugin#12]
I was able to successfully install this plugin on my last project but it doesn't seem to work now.  I even specified the same specific version with `...twitter-connect-plugin@0.6.0...` and it still failed.

```
Error: Failed to fetch plugin https://github.com/chroa/twitter-connect-plugin via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\RPO\AppData\Roaming\npm-cache\_logs\2018-02-23T19_17_13_124Z-debug.log
```

**Comment by rolinger** [comment]
hmmmm....it looks like when I specify the original plugin by build number it works.  Must be a change between the original plugin and the chora/ forked plugin.

This worked:
`cordova plugin add twitter-connect-plugin@0.6.0 --variable FABRIC_KEY ... `

**Comment by chroa** [comment]
I'm not 100% sure how the tagging/releases work but the following command does work:
`cordova plugin add https://github.com/chroa/twitter-connect-plugin#0.6.0 --variable FABRIC_KEY ...`

Nonetheless that version was created from the original repo.
I will close this as this is not exactly an issue.
