### ISSUE TITLE
Error building iOS project

### ISSUE THREAD

**Issue by miniskulljob** [chroa/twitter-connect-plugin#13]
Hello.
I don't know what happened, but I can't build my project because of this error:
```No visible @interface for 'TWTRSession' declares the selector 'userId'```
I could build it yesterday, but not today. I tried deleting the platform, plugins and node_modules folders and reinstalling everything from scratch, but nothing works.

```
cli packages:

    @ionic/cli-plugin-proxy : 1.5.7
    @ionic/cli-utils        : 1.19.1
    ionic (Ionic CLI)       : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.7
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    ios-sim           : 6.1.2
    Node              : v8.4.0
    npm               : 5.7.1
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b
```

**EDIT**
It seems like the problem comes from the changes you did in your last commit. As a temporary fix, I forked the project and reverted the commit so I could build my project again. I think it is a good practice to have a dev branch so people can test new changes until they are proven stable enough to be in the master branch.

**Comment by jarhed** [comment]
I too am having this issue

**Comment by chroa** [comment]
My bad guys, I know what the problem is. Thought I had committed my fix. >__>
Expect a fix in a few hours.

**Comment by chroa** [comment]
Everything should run fine now!

**Comment by miniskulljob** [comment]
@jarhed lol, I didn't know you could point to commits, thanks for the tip!

@chroa thanks, it works flawlessly now! I'll close the issue for you.
