### ISSUE TITLE
Failed login session

### ISSUE THREAD

**Issue by mrpower55** [chroa/twitter-connect-plugin#28]
Hello all,

hope you doing well

i have try this plugin and i add it well by using my twitter developer application key and secret but when i try it on android it is showing this message:

Failed login session

also i add 

<preference name="TwitterConsumerKey" value="" />
<preference name="TwitterConsumerSecret" value="" />

on my config.xml

so please if there is anything else i can do please let me know

Thanks

**Comment by mrpower55** [comment]
i solved it by adding
twittersdk://

on twitter application
go to my callback
add twittersdk://

and vola :D

**Comment by Ghayyas** [comment]
> twittersdk://

Can you show us through code?

**Comment by Ghayyas** [comment]
> Hello all,
> 
> hope you doing well
> 
> i have try this plugin and i add it well by using my twitter developer application key and secret but when i try it on android it is showing this message:
> 
> Failed login session
> 
> also i add
> 
> on my config.xml
> 
> so please if there is anything else i can do please let me know
> 
> Thanks

I resolve it by this..


     Go to your Platforms/android/build.gradle

Add the following code to the end.

      configurations {
	    all*.exclude group: 'com.android.support', module: 'support-v4'
       }
