### ISSUE TITLE
ios app works well on semulator but appstoreconnect doesn't approve it with twitter connect plugin.

### ISSUE THREAD

**Issue by SATPAL-BHARDWAJ** [chroa/twitter-connect-plugin#29]
I have used twitter connect for social login with my Ionic App. But it gives me appstoreconnect gives me this error

ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. 

I have used 
cordova-ios@6.1.0

In config xml file
`<preference name="WKWebViewOnly" value="true" />`

Then run the following command
`ionic Cordova prepare ios`

But nothing works. When I remove twitter connect plugin then it was accepted by appstoreconnect. That means the issue is with twitter connect plugin only.

**Comment by rolinger** [comment]
@SATPAL-BHARDWAJ - older thread, but if you haven't already found it you can try a fork by @tien271 - `cordova-plugin-twitter-connect-wkwebview`

**Comment by SATPAL-BHARDWAJ** [comment]
@rolinger Thank you so much for the reply, I will definitely try your suggestion.
