### ISSUE TITLE
Get user's email

### ISSUE THREAD

**Issue by trbsi** [chroa/twitter-connect-plugin#3]
Hi

Is it possible to get user's email as stated here https://dev.twitter.com/rest/reference/get/account/verify_credentials by using "include_email"

**Comment by chroa** [comment]
Hello! As it stands right now, it is not possible as I have not added that endpoint. :( You have to wait a little bit so I can implement and upload, or implement it yourself by following how the others were done.

**Comment by trbsi** [comment]
I'll wait for you to implement it.

**Comment by alphapilgrim** [comment]
@chroa any update on this, if I'm to understand this correctly. Current implementation doesn't return users email?

**Comment by chroa** [comment]
Master branch only had the show user endpoint implemented back then, and will be updated soon. The new twitter-kit-3 branch has both the show user and verify credentials implemented, only on android platform for now.

**Comment by chroa** [comment]
Verify credentials was implemented. It is now possible to get the user's email through that endpoint.
